import { ModelKey } from "./modelMetrics";

const ARCHIVED_MODEL_DIAGNOSES = {
  "cw_full": [
    "abdominal aortic aneurysm",
    "abdominal hernia",
    "abscess of nose",
    "abscess of the lung",
    "abscess of the pharynx",
    "acanthosis nigricans",
    "acariasis",
    "achalasia",
    "acne",
    "actinic keratosis",
    "acute bronchiolitis",
    "acute bronchitis",
    "acute bronchospasm",
    "acute glaucoma",
    "acute kidney injury",
    "acute otitis media",
    "acute pancreatitis",
    "acute respiratory distress syndrome (ards)",
    "acute sinusitis",
    "acute stress reaction",
    "adhesive capsulitis of the shoulder",
    "adjustment reaction",
    "adrenal adenoma",
    "alcohol abuse",
    "alcohol intoxication",
    "alcohol withdrawal",
    "alcoholic liver disease",
    "allergy",
    "allergy to animals",
    "alopecia",
    "alzheimer disease",
    "amblyopia",
    "amyotrophic lateral sclerosis (als)",
    "anal fissure",
    "anal fistula",
    "anemia",
    "anemia due to chronic kidney disease",
    "anemia due to malignancy",
    "anemia of chronic disease",
    "angina",
    "ankylosing spondylitis",
    "anxiety",
    "aortic valve disease",
    "aphthous ulcer",
    "aplastic anemia",
    "appendicitis",
    "arrhythmia",
    "arthritis of the hip",
    "ascending cholangitis",
    "asperger syndrome",
    "aspergillosis",
    "asthma",
    "astigmatism",
    "atelectasis",
    "athlete's foot",
    "atonic bladder",
    "atrial fibrillation",
    "atrial flutter",
    "atrophic skin condition",
    "atrophic vaginitis",
    "atrophy of the corpus cavernosum",
    "attention deficit hyperactivity disorder (adhd)",
    "autism",
    "autonomic nervous system disorder",
    "avascular necrosis",
    "balanitis",
    "bell palsy",
    "benign kidney cyst",
    "benign paroxysmal positional vertical (bppv)",
    "benign prostatic hyperplasia (bph)",
    "benign vaginal discharge (leukorrhea)",
    "bipolar disorder",
    "birth trauma",
    "bladder cancer",
    "bladder disorder",
    "bladder obstruction",
    "blepharitis",
    "bone cancer",
    "bone disorder",
    "bone spur of the calcaneous",
    "brachial neuritis",
    "brain cancer",
    "breast cyst",
    "breast infection (mastitis)",
    "broken tooth",
    "bunion",
    "burn",
    "bursitis",
    "callus",
    "carbon monoxide poisoning",
    "cardiac arrest",
    "cardiomyopathy",
    "carpal tunnel syndrome",
    "cataract",
    "celiac disease",
    "cellulitis or abscess of mouth",
    "central atherosclerosis",
    "central retinal artery or vein occlusion",
    "cerebral edema",
    "cerebral palsy",
    "cervical cancer",
    "cervical disorder",
    "cervicitis",
    "chalazion",
    "chickenpox",
    "chlamydia",
    "cholecystitis",
    "choledocholithiasis",
    "cholesteatoma",
    "chondromalacia of the patella",
    "chorioretinitis",
    "chronic back pain",
    "chronic constipation",
    "chronic glaucoma",
    "chronic inflammatory demyelinating polyneuropathy (cidp)",
    "chronic kidney disease",
    "chronic knee pain",
    "chronic obstructive pulmonary disease (copd)",
    "chronic otitis media",
    "chronic pain disorder",
    "chronic pancreatitis",
    "chronic rheumatic fever",
    "chronic sinusitis",
    "cirrhosis",
    "coagulation (bleeding) disorder",
    "cold sore",
    "colonic polyp",
    "colorectal cancer",
    "common cold",
    "complex regional pain syndrome",
    "concussion",
    "conduct disorder",
    "conductive hearing loss",
    "congenital heart defect",
    "congenital malformation syndrome",
    "conjunctivitis",
    "conjunctivitis due to allergy",
    "conjunctivitis due to bacteria",
    "conjunctivitis due to virus",
    "contact dermatitis",
    "conversion disorder",
    "cornea infection",
    "corneal abrasion",
    "corneal disorder",
    "coronary atherosclerosis",
    "cranial nerve palsy",
    "crohn disease",
    "croup",
    "crushing injury",
    "cryptococcosis",
    "cyst of the eyelid",
    "cystic fibrosis",
    "cysticercosis",
    "cystitis",
    "de quervain disease",
    "decubitus ulcer",
    "deep vein thrombosis (dvt)",
    "degenerative disc disease",
    "delirium",
    "dementia",
    "dental caries",
    "depression",
    "dermatitis due to sun exposure",
    "developmental disability",
    "deviated nasal septum",
    "diabetes insipidus",
    "diabetic ketoacidosis",
    "diabetic peripheral neuropathy",
    "diabetic retinopathy",
    "diaper rash",
    "dislocation of the ankle",
    "dislocation of the elbow",
    "dislocation of the finger",
    "dislocation of the foot",
    "dislocation of the shoulder",
    "dislocation of the vertebra",
    "dislocation of the wrist",
    "dissociative disorder",
    "diverticulitis",
    "diverticulosis",
    "down syndrome",
    "drug abuse",
    "drug abuse (barbiturates)",
    "drug abuse (cocaine)",
    "drug abuse (methamphetamine)",
    "drug abuse (opioids)",
    "drug poisoning due to medication",
    "drug reaction",
    "drug withdrawal",
    "dry eye of unknown cause",
    "dyshidrosis",
    "dysthymic disorder",
    "ear drum damage",
    "ear wax impaction",
    "eating disorder",
    "ectopic pregnancy",
    "ectropion",
    "eczema",
    "emphysema",
    "encephalitis",
    "endocarditis",
    "endometrial cancer",
    "endometrial hyperplasia",
    "endometriosis",
    "endophthalmitis",
    "envenomation from spider or animal bite",
    "ependymoma",
    "epididymitis",
    "epidural hemorrhage",
    "epilepsy",
    "erectile dysfunction",
    "erythema multiforme",
    "esophageal cancer",
    "esophagitis",
    "essential tremor",
    "eustachian tube dysfunction (ear disorder)",
    "extrapyramidal effect of drugs",
    "eye alignment disorder",
    "factitious disorder",
    "female genitalia infection",
    "female infertility of unknown cause",
    "fibroadenoma",
    "fibrocystic breast disease",
    "fibromyalgia",
    "flat feet",
    "floaters",
    "flu",
    "fluid overload",
    "folate deficiency",
    "food allergy",
    "foreign body in the ear",
    "foreign body in the eye",
    "foreign body in the gastrointestinal tract",
    "foreign body in the throat",
    "foreign body in the vagina",
    "fracture of the ankle",
    "fracture of the arm",
    "fracture of the facial bones",
    "fracture of the foot",
    "fracture of the hand",
    "fracture of the jaw",
    "fracture of the leg",
    "fracture of the neck",
    "fracture of the patella",
    "fracture of the pelvis",
    "fracture of the rib",
    "fracture of the shoulder",
    "fracture of the skull",
    "fracture of the vertebra",
    "frostbite",
    "fungal infection of the hair",
    "fungal infection of the skin",
    "galactorrhea of unknown cause",
    "gallstone",
    "ganglion cyst",
    "gastritis",
    "gastroduodenal ulcer",
    "gastroesophageal reflux disease (gerd)",
    "gastrointestinal hemorrhage",
    "gastroparesis",
    "genital herpes",
    "gestational diabetes",
    "glaucoma",
    "glucocorticoid deficiency",
    "goiter",
    "gonorrhea",
    "gout",
    "granuloma inguinale",
    "graves disease",
    "guillain barre syndrome",
    "gum disease",
    "gynecomastia",
    "head and neck cancer",
    "head injury",
    "headache after lumbar puncture",
    "heart attack",
    "heart block",
    "heart contusion",
    "heart failure",
    "heat exhaustion",
    "hemangioma",
    "hematoma",
    "hemiplegia",
    "hemolytic anemia",
    "hemophilia",
    "hemorrhoids",
    "hepatic encephalopathy",
    "hepatitis due to a toxin",
    "herniated disk",
    "herpangina",
    "hiatal hernia",
    "hidradenitis suppurativa",
    "hirschsprung disease",
    "hirsutism",
    "hormone disorder",
    "hpv",
    "hydatidiform mole",
    "hydrocele of the testicle",
    "hydrocephalus",
    "hydronephrosis",
    "hypercalcemia",
    "hyperemesis gravidarum",
    "hyperhidrosis",
    "hyperkalemia",
    "hypernatremia",
    "hyperopia",
    "hypertension of pregnancy",
    "hypertensive heart disease",
    "hypocalcemia",
    "hypoglycemia",
    "hypokalemia",
    "hyponatremia",
    "hypothermia",
    "hypothyroidism",
    "hypovolemia",
    "idiopathic absence of menstruation",
    "idiopathic excessive menstruation",
    "idiopathic infrequent menstruation",
    "idiopathic irregular menstrual cycle",
    "idiopathic nonmenstrual bleeding",
    "idiopathic painful menstruation",
    "ileus",
    "impetigo",
    "impulse control disorder",
    "indigestion",
    "induced abortion",
    "infection of open wound",
    "infectious gastroenteritis",
    "ingrown toe nail",
    "inguinal hernia",
    "injury of the ankle",
    "injury to internal organ",
    "injury to the abdomen",
    "injury to the arm",
    "injury to the face",
    "injury to the hand",
    "injury to the hip",
    "injury to the knee",
    "injury to the leg",
    "injury to the shoulder",
    "injury to the spinal cord",
    "injury to the trunk",
    "insect bite",
    "interstitial lung disease",
    "intertrigo (skin condition)",
    "intestinal cancer",
    "intestinal disease",
    "intestinal malabsorption",
    "intestinal obstruction",
    "intracerebral hemorrhage",
    "intracranial abscess",
    "intracranial hemorrhage",
    "iridocyclitis",
    "iron deficiency anemia",
    "irritable bowel syndrome",
    "ischemia of the bowel",
    "ischemic heart disease",
    "itching of unknown cause",
    "jaw disorder",
    "joint effusion",
    "juvenile rheumatoid arthritis",
    "kidney cancer",
    "kidney disease due to longstanding hypertension",
    "kidney failure",
    "kidney stone",
    "knee ligament or meniscus tear",
    "labyrinthitis",
    "lactose intolerance",
    "laryngitis",
    "lateral epicondylitis (tennis elbow)",
    "leukemia",
    "lewy body dementia",
    "lice",
    "lichen simplex",
    "lipoma",
    "liver cancer",
    "liver disease",
    "lumbago",
    "lung cancer",
    "lung contusion",
    "lyme disease",
    "lymphadenitis",
    "lymphedema",
    "lymphogranuloma venereum",
    "lymphoma",
    "macular degeneration",
    "magnesium deficiency",
    "malaria",
    "male genitalia infection",
    "malignant hypertension",
    "marijuana abuse",
    "mastectomy",
    "mastoiditis",
    "melanoma",
    "meniere disease",
    "meningioma",
    "meningitis",
    "menopause",
    "metabolic disorder",
    "metastatic cancer",
    "migraine",
    "missed abortion",
    "mitral valve disease",
    "mittelschmerz",
    "molluscum contagiosum",
    "mononeuritis",
    "mononucleosis",
    "moyamoya disease",
    "mucositis",
    "multiple myeloma",
    "multiple sclerosis",
    "mumps",
    "muscle spasm",
    "muscular dystrophy",
    "myasthenia gravis",
    "myoclonus",
    "myopia",
    "myositis",
    "narcolepsy",
    "nasal polyp",
    "neonatal jaundice",
    "nerve impingement near the shoulder",
    "neuralgia",
    "neurofibromatosis",
    "neuropathy due to drugs",
    "neurosis",
    "nonalcoholic liver disease (nash)",
    "noninfectious gastroenteritis",
    "normal pressure hydrocephalus",
    "nose disorder",
    "obsessive compulsive disorder (ocd)",
    "obstructive sleep apnea (osa)",
    "onychomycosis",
    "open wound of the arm",
    "open wound of the ear",
    "open wound of the eye",
    "open wound of the foot",
    "open wound of the lip",
    "open wound of the mouth",
    "open wound of the neck",
    "open wound of the nose",
    "oppositional disorder",
    "optic neuritis",
    "oral mucosal lesion",
    "oral thrush (yeast infection)",
    "orbital cellulitis",
    "orthostatic hypotension",
    "osteoarthritis",
    "osteochondroma",
    "osteochondrosis",
    "osteomyelitis",
    "osteoporosis",
    "otitis externa (swimmer's ear)",
    "otitis media",
    "otosclerosis",
    "ovarian cancer",
    "ovarian cyst",
    "ovarian torsion",
    "overflow incontinence",
    "pain after an operation",
    "pain disorder affecting the neck",
    "pancreatic cancer",
    "panic attack",
    "panic disorder",
    "parasitic disease",
    "parathyroid adenoma",
    "parkinson disease",
    "paronychia",
    "paroxysmal supraventricular tachycardia",
    "paroxysmal ventricular tachycardia",
    "pelvic inflammatory disease",
    "pelvic organ prolapse",
    "pericarditis",
    "peripheral arterial disease",
    "peripheral arterial embolism",
    "peripheral nerve disorder",
    "perirectal infection",
    "peritonitis",
    "peritonsillar abscess",
    "persistent vomiting of unknown cause",
    "personality disorder",
    "peyronie disease",
    "pharyngitis",
    "phimosis",
    "pilonidal cyst",
    "pinworm infection",
    "pituitary adenoma",
    "pituitary disorder",
    "pityriasis rosea",
    "placental abruption",
    "plantar fasciitis",
    "pleural effusion",
    "pneumoconiosis",
    "pneumonia",
    "pneumothorax",
    "poisoning due to analgesics",
    "poisoning due to anticonvulsants",
    "poisoning due to antidepressants",
    "poisoning due to antihypertensives",
    "poisoning due to antimicrobial drugs",
    "poisoning due to antipsychotics",
    "poisoning due to ethylene glycol",
    "poisoning due to gas",
    "poisoning due to sedatives",
    "polycystic kidney disease",
    "polycystic ovarian syndrome (pcos)",
    "polycythemia vera",
    "polymyalgia rheumatica",
    "post-traumatic stress disorder (ptsd)",
    "postoperative infection",
    "postpartum depression",
    "preeclampsia",
    "pregnancy",
    "premature atrial contractions (pacs)",
    "premature ovarian failure",
    "premature ventricular contractions (pvcs)",
    "premenstrual tension syndrome",
    "presbyacusis",
    "presbyopia",
    "primary immunodeficiency",
    "primary insomnia",
    "primary kidney disease",
    "problem during pregnancy",
    "prostate cancer",
    "prostatitis",
    "protein deficiency",
    "pseudohypoparathyroidism",
    "pseudotumor cerebri",
    "psoriasis",
    "psychosexual disorder",
    "psychotic disorder",
    "pterygium",
    "pulmonary congestion",
    "pulmonary embolism",
    "pulmonary eosinophilia",
    "pulmonary fibrosis",
    "pulmonary hypertension",
    "pulmonic valve disease",
    "pyelonephritis",
    "pyloric stenosis",
    "pyogenic skin infection",
    "raynaud disease",
    "reactive arthritis",
    "rectal disorder",
    "restless leg syndrome",
    "retinal detachment",
    "retinopathy due to high blood pressure",
    "rhabdomyolysis",
    "rheumatoid arthritis",
    "rosacea",
    "rotator cuff injury",
    "salivary gland disorder",
    "sarcoidosis",
    "scabies",
    "scar",
    "scarlet fever",
    "schizophrenia",
    "sciatica",
    "scleritis",
    "scleroderma",
    "scoliosis",
    "seasonal allergies (hay fever)",
    "sebaceous cyst",
    "seborrheic dermatitis",
    "seborrheic keratosis",
    "sensorineural hearing loss",
    "sepsis",
    "septic arthritis",
    "shingles (herpes zoster)",
    "sialoadenitis",
    "sick sinus syndrome",
    "sickle cell anemia",
    "sickle cell crisis",
    "sinus bradycardia",
    "sjogren syndrome",
    "skin cancer",
    "skin disorder",
    "skin pigmentation disorder",
    "skin polyp",
    "smoking or tobacco addiction",
    "social phobia",
    "soft tissue sarcoma",
    "somatization disorder",
    "spermatocele",
    "spina bifida",
    "spinal stenosis",
    "spondylitis",
    "spondylolisthesis",
    "spondylosis",
    "spontaneous abortion",
    "sprain or strain",
    "stenosis of the tear duct",
    "stomach cancer",
    "strep throat",
    "stress incontinence",
    "stricture of the esophagus",
    "stroke",
    "stye",
    "subacute thyroiditis",
    "subarachnoid hemorrhage",
    "subconjunctival hemorrhage",
    "subdural hemorrhage",
    "substance-related mental disorder",
    "syphilis",
    "syringomyelia",
    "systemic lupus erythematosis (sle)",
    "teething syndrome",
    "temporary or benign blood in urine",
    "temporomandibular joint disorder",
    "tendinitis",
    "tension headache",
    "testicular cancer",
    "testicular disorder",
    "testicular torsion",
    "thoracic aortic aneurysm",
    "thoracic outlet syndrome",
    "threatened pregnancy",
    "thrombocytopenia",
    "thrombophlebitis",
    "thyroid disease",
    "thyroid nodule",
    "tic (movement) disorder",
    "tietze syndrome",
    "tinnitus of unknown cause",
    "tonsillar hypertrophy",
    "tonsillitis",
    "tooth abscess",
    "tooth disorder",
    "torticollis",
    "tourette syndrome",
    "toxic multinodular goiter",
    "toxoplasmosis",
    "tracheitis",
    "transient ischemic attack",
    "trichiasis",
    "trichinosis",
    "trichomonas infection",
    "trigeminal neuralgia",
    "trigger finger (finger disorder)",
    "tuberculosis",
    "ulcerative colitis",
    "urethral disorder",
    "urethral stricture",
    "urethral valves",
    "urethritis",
    "urge incontinence",
    "urinary tract infection",
    "urinary tract obstruction",
    "uterine atony",
    "uterine fibroids",
    "uveitis",
    "vaginal cyst",
    "vaginal yeast infection",
    "vaginismus",
    "vaginitis",
    "varicocele of the testicles",
    "varicose veins",
    "vasculitis",
    "venous insufficiency",
    "vertebrobasilar insufficiency",
    "vesicoureteral reflux",
    "viral exanthem",
    "viral hepatitis",
    "viral warts",
    "vitamin b12 deficiency",
    "vitamin d deficiency",
    "vitreous degeneration",
    "vitreous hemorrhage",
    "vocal cord polyp",
    "volvulus",
    "vulvar disorder",
    "vulvodynia",
    "white blood cell disease",
    "whooping cough",
    "wilson disease",
    "yeast infection",
    "zenker diverticulum"
  ],
  "ae_t100": [
    "abdominal aortic aneurysm",
    "abdominal hernia",
    "abscess of nose",
    "abscess of the pharynx",
    "acne",
    "actinic keratosis",
    "acute bronchiolitis",
    "acute bronchitis",
    "acute bronchospasm",
    "acute glaucoma",
    "acute kidney injury",
    "acute otitis media",
    "acute pancreatitis",
    "acute respiratory distress syndrome (ards)",
    "acute sinusitis",
    "acute stress reaction",
    "adjustment reaction",
    "alcohol abuse",
    "alcohol intoxication",
    "alcohol withdrawal",
    "alcoholic liver disease",
    "allergy",
    "alopecia",
    "alzheimer disease",
    "anal fissure",
    "anemia",
    "angina",
    "ankylosing spondylitis",
    "anxiety",
    "aortic valve disease",
    "aphthous ulcer",
    "appendicitis",
    "arrhythmia",
    "arthritis of the hip",
    "asperger syndrome",
    "asthma",
    "astigmatism",
    "athlete's foot",
    "atrial flutter",
    "atrophic skin condition",
    "atrophic vaginitis",
    "attention deficit hyperactivity disorder (adhd)",
    "autism",
    "balanitis",
    "bell palsy",
    "benign kidney cyst",
    "benign paroxysmal positional vertical (bppv)",
    "benign prostatic hyperplasia (bph)",
    "benign vaginal discharge (leukorrhea)",
    "bipolar disorder",
    "bladder cancer",
    "bladder disorder",
    "bladder obstruction",
    "blepharitis",
    "bone disorder",
    "brachial neuritis",
    "brain cancer",
    "breast infection (mastitis)",
    "broken tooth",
    "bursitis",
    "callus",
    "cardiac arrest",
    "cardiomyopathy",
    "carpal tunnel syndrome",
    "cataract",
    "celiac disease",
    "cellulitis or abscess of mouth",
    "cerebral edema",
    "cerebral palsy",
    "cervicitis",
    "chalazion",
    "chickenpox",
    "chlamydia",
    "cholecystitis",
    "choledocholithiasis",
    "chronic back pain",
    "chronic constipation",
    "chronic glaucoma",
    "chronic knee pain",
    "chronic obstructive pulmonary disease (copd)",
    "chronic otitis media",
    "chronic pain disorder",
    "chronic pancreatitis",
    "chronic rheumatic fever",
    "chronic sinusitis",
    "cirrhosis",
    "cold sore",
    "colonic polyp",
    "common cold",
    "complex regional pain syndrome",
    "concussion",
    "conduct disorder",
    "conductive hearing loss",
    "conjunctivitis",
    "conjunctivitis due to allergy",
    "conjunctivitis due to bacteria",
    "conjunctivitis due to virus",
    "contact dermatitis",
    "cornea infection",
    "corneal abrasion",
    "corneal disorder",
    "coronary atherosclerosis",
    "cranial nerve palsy",
    "crohn disease",
    "croup",
    "cystitis",
    "deep vein thrombosis (dvt)",
    "degenerative disc disease",
    "delirium",
    "dementia",
    "dental caries",
    "depression",
    "dermatitis due to sun exposure",
    "developmental disability",
    "deviated nasal septum",
    "diabetic ketoacidosis",
    "diabetic peripheral neuropathy",
    "diabetic retinopathy",
    "diaper rash",
    "diverticulitis",
    "diverticulosis",
    "down syndrome",
    "drug abuse",
    "drug abuse (cocaine)",
    "drug abuse (methamphetamine)",
    "drug abuse (opioids)",
    "drug poisoning due to medication",
    "drug reaction",
    "drug withdrawal",
    "dry eye of unknown cause",
    "dysthymic disorder",
    "ear drum damage",
    "ear wax impaction",
    "eating disorder",
    "ectopic pregnancy",
    "eczema",
    "endometriosis",
    "envenomation from spider or animal bite",
    "epididymitis",
    "erectile dysfunction",
    "esophagitis",
    "essential tremor",
    "eustachian tube dysfunction (ear disorder)",
    "eye alignment disorder",
    "female genitalia infection",
    "fibromyalgia",
    "flu",
    "fluid overload",
    "food allergy",
    "foreign body in the eye",
    "foreign body in the gastrointestinal tract",
    "foreign body in the throat",
    "fracture of the arm",
    "fracture of the facial bones",
    "fracture of the hand",
    "fracture of the leg",
    "fracture of the pelvis",
    "fracture of the rib",
    "fracture of the shoulder",
    "fracture of the vertebra",
    "fungal infection of the hair",
    "fungal infection of the skin",
    "gallstone",
    "ganglion cyst",
    "gastritis",
    "gastroduodenal ulcer",
    "gastroesophageal reflux disease (gerd)",
    "gastrointestinal hemorrhage",
    "gastroparesis",
    "genital herpes",
    "glaucoma",
    "gonorrhea",
    "gout",
    "graves disease",
    "gum disease",
    "head and neck cancer",
    "head injury",
    "headache after lumbar puncture",
    "heart attack",
    "heart block",
    "heart failure",
    "heat exhaustion",
    "hemangioma",
    "hemiplegia",
    "hemorrhoids",
    "hepatitis due to a toxin",
    "herniated disk",
    "herpangina",
    "hiatal hernia",
    "hidradenitis suppurativa",
    "hydrocele of the testicle",
    "hydrocephalus",
    "hydronephrosis",
    "hyperemesis gravidarum",
    "hyperkalemia",
    "hyperopia",
    "hypertensive heart disease",
    "hypoglycemia",
    "hypokalemia",
    "hyponatremia",
    "hypovolemia",
    "idiopathic absence of menstruation",
    "idiopathic excessive menstruation",
    "idiopathic irregular menstrual cycle",
    "idiopathic painful menstruation",
    "ileus",
    "impetigo",
    "impulse control disorder",
    "indigestion",
    "induced abortion",
    "infectious gastroenteritis",
    "ingrown toe nail",
    "inguinal hernia",
    "injury of the ankle",
    "injury to internal organ",
    "injury to the arm",
    "injury to the face",
    "injury to the hand",
    "injury to the leg",
    "injury to the shoulder",
    "injury to the trunk",
    "insect bite",
    "interstitial lung disease",
    "intertrigo (skin condition)",
    "intestinal disease",
    "intestinal malabsorption",
    "intestinal obstruction",
    "intracerebral hemorrhage",
    "intracranial hemorrhage",
    "iridocyclitis",
    "iron deficiency anemia",
    "irritable bowel syndrome",
    "ischemia of the bowel",
    "ischemic heart disease",
    "itching of unknown cause",
    "jaw disorder",
    "joint effusion",
    "kidney failure",
    "kidney stone",
    "knee ligament or meniscus tear",
    "labyrinthitis",
    "lactose intolerance",
    "laryngitis",
    "lateral epicondylitis (tennis elbow)",
    "lipoma",
    "liver disease",
    "lumbago",
    "lyme disease",
    "lymphadenitis",
    "lymphedema",
    "lymphoma",
    "macular degeneration",
    "male genitalia infection",
    "malignant hypertension",
    "marijuana abuse",
    "mastoiditis",
    "melanoma",
    "meniere disease",
    "meningitis",
    "migraine",
    "missed abortion",
    "mitral valve disease",
    "molluscum contagiosum",
    "mononeuritis",
    "mononucleosis",
    "mucositis",
    "multiple sclerosis",
    "muscle spasm",
    "myasthenia gravis",
    "myopia",
    "myositis",
    "narcolepsy",
    "nasal polyp",
    "nerve impingement near the shoulder",
    "neuralgia",
    "neurosis",
    "noninfectious gastroenteritis",
    "nose disorder",
    "obsessive compulsive disorder (ocd)",
    "obstructive sleep apnea (osa)",
    "onychomycosis",
    "oppositional disorder",
    "oral mucosal lesion",
    "oral thrush (yeast infection)",
    "orbital cellulitis",
    "orthostatic hypotension",
    "osteoarthritis",
    "osteochondroma",
    "osteochondrosis",
    "osteomyelitis",
    "osteoporosis",
    "otitis externa (swimmer's ear)",
    "otitis media",
    "ovarian cyst",
    "overflow incontinence",
    "pain after an operation",
    "pain disorder affecting the neck",
    "pancreatic cancer",
    "panic attack",
    "panic disorder",
    "parkinson disease",
    "paronychia",
    "paroxysmal supraventricular tachycardia",
    "paroxysmal ventricular tachycardia",
    "pelvic inflammatory disease",
    "pelvic organ prolapse",
    "pericarditis",
    "peripheral arterial disease",
    "peripheral arterial embolism",
    "peripheral nerve disorder",
    "perirectal infection",
    "peritonitis",
    "peritonsillar abscess",
    "persistent vomiting of unknown cause",
    "personality disorder",
    "pilonidal cyst",
    "plantar fasciitis",
    "pleural effusion",
    "pneumonia",
    "pneumothorax",
    "poisoning due to gas",
    "poisoning due to sedatives",
    "polycystic kidney disease",
    "polycystic ovarian syndrome (pcos)",
    "polymyalgia rheumatica",
    "post-traumatic stress disorder (ptsd)",
    "postoperative infection",
    "postpartum depression",
    "preeclampsia",
    "premature atrial contractions (pacs)",
    "premature ventricular contractions (pvcs)",
    "premenstrual tension syndrome",
    "presbyopia",
    "primary insomnia",
    "problem during pregnancy",
    "prostate cancer",
    "prostatitis",
    "psoriasis",
    "psychosexual disorder",
    "psychotic disorder",
    "pterygium",
    "pulmonary congestion",
    "pulmonary embolism",
    "pulmonary eosinophilia",
    "pulmonary fibrosis",
    "pulmonary hypertension",
    "pyelonephritis",
    "pyogenic skin infection",
    "rectal disorder",
    "restless leg syndrome",
    "retinal detachment",
    "retinopathy due to high blood pressure",
    "rheumatoid arthritis",
    "rosacea",
    "rotator cuff injury",
    "sarcoidosis",
    "scabies",
    "scar",
    "schizophrenia",
    "sciatica",
    "scleroderma",
    "scoliosis",
    "seasonal allergies (hay fever)",
    "sebaceous cyst",
    "seborrheic dermatitis",
    "seborrheic keratosis",
    "sensorineural hearing loss",
    "sepsis",
    "shingles (herpes zoster)",
    "sialoadenitis",
    "sick sinus syndrome",
    "sickle cell anemia",
    "sickle cell crisis",
    "sinus bradycardia",
    "skin cancer",
    "skin disorder",
    "skin pigmentation disorder",
    "skin polyp",
    "smoking or tobacco addiction",
    "social phobia",
    "soft tissue sarcoma",
    "spinal stenosis",
    "spondylitis",
    "spondylolisthesis",
    "spondylosis",
    "spontaneous abortion",
    "sprain or strain",
    "stenosis of the tear duct",
    "stomach cancer",
    "strep throat",
    "stress incontinence",
    "stroke",
    "stye",
    "subarachnoid hemorrhage",
    "subconjunctival hemorrhage",
    "subdural hemorrhage",
    "substance-related mental disorder",
    "systemic lupus erythematosis (sle)",
    "teething syndrome",
    "temporary or benign blood in urine",
    "temporomandibular joint disorder",
    "tendinitis",
    "tension headache",
    "thoracic aortic aneurysm",
    "thoracic outlet syndrome",
    "threatened pregnancy",
    "thrombocytopenia",
    "thrombophlebitis",
    "thyroid nodule",
    "tietze syndrome",
    "tinnitus of unknown cause",
    "tonsillar hypertrophy",
    "tonsillitis",
    "tooth abscess",
    "tooth disorder",
    "torticollis",
    "tracheitis",
    "transient ischemic attack",
    "trichomonas infection",
    "trigeminal neuralgia",
    "ulcerative colitis",
    "urethral disorder",
    "urethral stricture",
    "urethritis",
    "urge incontinence",
    "urinary tract infection",
    "urinary tract obstruction",
    "uterine atony",
    "uterine fibroids",
    "vaginal cyst",
    "vaginal yeast infection",
    "vaginitis",
    "varicocele of the testicles",
    "varicose veins",
    "vasculitis",
    "venous insufficiency",
    "viral exanthem",
    "viral warts",
    "vitreous degeneration",
    "vulvar disorder",
    "vulvodynia",
    "white blood cell disease",
    "yeast infection"
  ],
  "ae_t200": [
    "abdominal hernia",
    "abscess of nose",
    "abscess of the pharynx",
    "acne",
    "actinic keratosis",
    "acute bronchiolitis",
    "acute bronchitis",
    "acute bronchospasm",
    "acute glaucoma",
    "acute kidney injury",
    "acute otitis media",
    "acute pancreatitis",
    "acute respiratory distress syndrome (ards)",
    "acute sinusitis",
    "acute stress reaction",
    "adjustment reaction",
    "alcohol abuse",
    "alcohol intoxication",
    "alcohol withdrawal",
    "alcoholic liver disease",
    "allergy",
    "alopecia",
    "alzheimer disease",
    "anal fissure",
    "anemia",
    "angina",
    "ankylosing spondylitis",
    "anxiety",
    "aortic valve disease",
    "aphthous ulcer",
    "appendicitis",
    "arrhythmia",
    "arthritis of the hip",
    "asperger syndrome",
    "asthma",
    "astigmatism",
    "athlete's foot",
    "atrial flutter",
    "atrophic skin condition",
    "atrophic vaginitis",
    "attention deficit hyperactivity disorder (adhd)",
    "autism",
    "balanitis",
    "bell palsy",
    "benign kidney cyst",
    "benign paroxysmal positional vertical (bppv)",
    "benign prostatic hyperplasia (bph)",
    "benign vaginal discharge (leukorrhea)",
    "bipolar disorder",
    "bladder disorder",
    "bladder obstruction",
    "blepharitis",
    "bone disorder",
    "brachial neuritis",
    "brain cancer",
    "breast infection (mastitis)",
    "bursitis",
    "callus",
    "cardiac arrest",
    "cardiomyopathy",
    "carpal tunnel syndrome",
    "cataract",
    "cervicitis",
    "chalazion",
    "cholecystitis",
    "choledocholithiasis",
    "chronic back pain",
    "chronic constipation",
    "chronic glaucoma",
    "chronic obstructive pulmonary disease (copd)",
    "chronic otitis media",
    "chronic pain disorder",
    "chronic pancreatitis",
    "chronic sinusitis",
    "cirrhosis",
    "colonic polyp",
    "common cold",
    "complex regional pain syndrome",
    "concussion",
    "conduct disorder",
    "conductive hearing loss",
    "conjunctivitis",
    "conjunctivitis due to allergy",
    "conjunctivitis due to virus",
    "contact dermatitis",
    "cornea infection",
    "corneal abrasion",
    "corneal disorder",
    "cranial nerve palsy",
    "crohn disease",
    "croup",
    "cystitis",
    "deep vein thrombosis (dvt)",
    "degenerative disc disease",
    "delirium",
    "dementia",
    "dental caries",
    "depression",
    "dermatitis due to sun exposure",
    "developmental disability",
    "deviated nasal septum",
    "diabetic ketoacidosis",
    "diabetic peripheral neuropathy",
    "diabetic retinopathy",
    "diaper rash",
    "diverticulitis",
    "diverticulosis",
    "drug abuse",
    "drug abuse (cocaine)",
    "drug abuse (methamphetamine)",
    "drug abuse (opioids)",
    "drug poisoning due to medication",
    "drug reaction",
    "drug withdrawal",
    "dry eye of unknown cause",
    "dysthymic disorder",
    "ear drum damage",
    "ear wax impaction",
    "eating disorder",
    "ectopic pregnancy",
    "eczema",
    "endometriosis",
    "envenomation from spider or animal bite",
    "epididymitis",
    "erectile dysfunction",
    "esophagitis",
    "eustachian tube dysfunction (ear disorder)",
    "eye alignment disorder",
    "fibromyalgia",
    "flu",
    "fluid overload",
    "food allergy",
    "foreign body in the eye",
    "fracture of the arm",
    "fracture of the facial bones",
    "fracture of the leg",
    "fracture of the rib",
    "fracture of the vertebra",
    "fungal infection of the hair",
    "fungal infection of the skin",
    "gallstone",
    "ganglion cyst",
    "gastritis",
    "gastroduodenal ulcer",
    "gastroesophageal reflux disease (gerd)",
    "gastrointestinal hemorrhage",
    "genital herpes",
    "glaucoma",
    "gout",
    "graves disease",
    "gum disease",
    "head and neck cancer",
    "heart attack",
    "heart block",
    "heart failure",
    "heat exhaustion",
    "hemangioma",
    "hemiplegia",
    "hemorrhoids",
    "hepatitis due to a toxin",
    "herniated disk",
    "herpangina",
    "hiatal hernia",
    "hydrocele of the testicle",
    "hydronephrosis",
    "hyperemesis gravidarum",
    "hyperkalemia",
    "hypertensive heart disease",
    "hypoglycemia",
    "hypokalemia",
    "hyponatremia",
    "hypovolemia",
    "idiopathic absence of menstruation",
    "idiopathic excessive menstruation",
    "idiopathic irregular menstrual cycle",
    "idiopathic painful menstruation",
    "ileus",
    "impetigo",
    "impulse control disorder",
    "indigestion",
    "induced abortion",
    "infectious gastroenteritis",
    "ingrown toe nail",
    "inguinal hernia",
    "injury to the arm",
    "injury to the face",
    "injury to the leg",
    "injury to the shoulder",
    "injury to the trunk",
    "insect bite",
    "interstitial lung disease",
    "intestinal disease",
    "intestinal obstruction",
    "intracerebral hemorrhage",
    "intracranial hemorrhage",
    "iridocyclitis",
    "iron deficiency anemia",
    "irritable bowel syndrome",
    "ischemia of the bowel",
    "ischemic heart disease",
    "itching of unknown cause",
    "jaw disorder",
    "joint effusion",
    "kidney failure",
    "kidney stone",
    "labyrinthitis",
    "laryngitis",
    "lateral epicondylitis (tennis elbow)",
    "lipoma",
    "liver disease",
    "lyme disease",
    "lymphadenitis",
    "lymphedema",
    "macular degeneration",
    "marijuana abuse",
    "melanoma",
    "meniere disease",
    "meningitis",
    "migraine",
    "missed abortion",
    "mitral valve disease",
    "molluscum contagiosum",
    "mononeuritis",
    "mononucleosis",
    "mucositis",
    "multiple sclerosis",
    "muscle spasm",
    "myopia",
    "nasal polyp",
    "nerve impingement near the shoulder",
    "neuralgia",
    "neurosis",
    "noninfectious gastroenteritis",
    "nose disorder",
    "obsessive compulsive disorder (ocd)",
    "obstructive sleep apnea (osa)",
    "onychomycosis",
    "oppositional disorder",
    "oral mucosal lesion",
    "oral thrush (yeast infection)",
    "orthostatic hypotension",
    "osteoarthritis",
    "osteochondroma",
    "osteoporosis",
    "otitis externa (swimmer's ear)",
    "otitis media",
    "ovarian cyst",
    "overflow incontinence",
    "pain after an operation",
    "pain disorder affecting the neck",
    "pancreatic cancer",
    "panic disorder",
    "parkinson disease",
    "paronychia",
    "paroxysmal supraventricular tachycardia",
    "paroxysmal ventricular tachycardia",
    "pelvic inflammatory disease",
    "pelvic organ prolapse",
    "peripheral nerve disorder",
    "peritonitis",
    "peritonsillar abscess",
    "personality disorder",
    "pilonidal cyst",
    "pleural effusion",
    "pneumonia",
    "pneumothorax",
    "polycystic ovarian syndrome (pcos)",
    "post-traumatic stress disorder (ptsd)",
    "postpartum depression",
    "preeclampsia",
    "premature atrial contractions (pacs)",
    "premature ventricular contractions (pvcs)",
    "presbyopia",
    "problem during pregnancy",
    "prostatitis",
    "psoriasis",
    "psychotic disorder",
    "pterygium",
    "pulmonary congestion",
    "pulmonary embolism",
    "pulmonary hypertension",
    "pyelonephritis",
    "pyogenic skin infection",
    "rectal disorder",
    "restless leg syndrome",
    "retinal detachment",
    "rheumatoid arthritis",
    "rosacea",
    "sarcoidosis",
    "scar",
    "schizophrenia",
    "sciatica",
    "scleroderma",
    "seasonal allergies (hay fever)",
    "sebaceous cyst",
    "seborrheic dermatitis",
    "seborrheic keratosis",
    "sensorineural hearing loss",
    "sepsis",
    "shingles (herpes zoster)",
    "sialoadenitis",
    "sickle cell anemia",
    "sickle cell crisis",
    "sinus bradycardia",
    "skin cancer",
    "skin disorder",
    "skin pigmentation disorder",
    "skin polyp",
    "smoking or tobacco addiction",
    "social phobia",
    "spinal stenosis",
    "spondylitis",
    "spondylolisthesis",
    "spondylosis",
    "spontaneous abortion",
    "sprain or strain",
    "strep throat",
    "stress incontinence",
    "stroke",
    "stye",
    "subconjunctival hemorrhage",
    "substance-related mental disorder",
    "teething syndrome",
    "temporary or benign blood in urine",
    "temporomandibular joint disorder",
    "tendinitis",
    "tension headache",
    "threatened pregnancy",
    "thrombophlebitis",
    "thyroid nodule",
    "tietze syndrome",
    "tinnitus of unknown cause",
    "tonsillar hypertrophy",
    "tonsillitis",
    "tooth abscess",
    "tooth disorder",
    "torticollis",
    "transient ischemic attack",
    "trichomonas infection",
    "trigeminal neuralgia",
    "ulcerative colitis",
    "urethral disorder",
    "urethral stricture",
    "urethritis",
    "urge incontinence",
    "urinary tract infection",
    "urinary tract obstruction",
    "uterine atony",
    "uterine fibroids",
    "vaginal cyst",
    "vaginal yeast infection",
    "vaginitis",
    "varicocele of the testicles",
    "vasculitis",
    "venous insufficiency",
    "viral exanthem",
    "viral warts",
    "vitreous degeneration",
    "vulvodynia",
    "white blood cell disease",
    "yeast infection"
  ],
  "ae_t300": [
    "abdominal hernia",
    "abscess of the pharynx",
    "acne",
    "actinic keratosis",
    "acute bronchiolitis",
    "acute bronchitis",
    "acute bronchospasm",
    "acute kidney injury",
    "acute otitis media",
    "acute pancreatitis",
    "acute respiratory distress syndrome (ards)",
    "acute sinusitis",
    "acute stress reaction",
    "adjustment reaction",
    "alcohol abuse",
    "alcohol intoxication",
    "alcohol withdrawal",
    "allergy",
    "alopecia",
    "alzheimer disease",
    "anemia",
    "angina",
    "ankylosing spondylitis",
    "anxiety",
    "aortic valve disease",
    "appendicitis",
    "arthritis of the hip",
    "asperger syndrome",
    "asthma",
    "astigmatism",
    "athlete's foot",
    "atrophic skin condition",
    "atrophic vaginitis",
    "attention deficit hyperactivity disorder (adhd)",
    "autism",
    "balanitis",
    "bell palsy",
    "benign paroxysmal positional vertical (bppv)",
    "benign prostatic hyperplasia (bph)",
    "benign vaginal discharge (leukorrhea)",
    "bipolar disorder",
    "bladder disorder",
    "bladder obstruction",
    "blepharitis",
    "brachial neuritis",
    "breast infection (mastitis)",
    "bursitis",
    "callus",
    "cardiac arrest",
    "cardiomyopathy",
    "carpal tunnel syndrome",
    "cataract",
    "cervicitis",
    "chalazion",
    "cholecystitis",
    "choledocholithiasis",
    "chronic back pain",
    "chronic constipation",
    "chronic glaucoma",
    "chronic obstructive pulmonary disease (copd)",
    "chronic otitis media",
    "chronic pain disorder",
    "chronic sinusitis",
    "cirrhosis",
    "colonic polyp",
    "common cold",
    "complex regional pain syndrome",
    "concussion",
    "conduct disorder",
    "conductive hearing loss",
    "conjunctivitis",
    "conjunctivitis due to allergy",
    "conjunctivitis due to virus",
    "contact dermatitis",
    "cornea infection",
    "corneal abrasion",
    "corneal disorder",
    "cranial nerve palsy",
    "crohn disease",
    "croup",
    "cystitis",
    "degenerative disc disease",
    "delirium",
    "dementia",
    "dental caries",
    "depression",
    "dermatitis due to sun exposure",
    "developmental disability",
    "deviated nasal septum",
    "diabetic ketoacidosis",
    "diabetic peripheral neuropathy",
    "diabetic retinopathy",
    "diaper rash",
    "diverticulitis",
    "diverticulosis",
    "drug abuse",
    "drug abuse (methamphetamine)",
    "drug abuse (opioids)",
    "drug reaction",
    "dry eye of unknown cause",
    "dysthymic disorder",
    "ear drum damage",
    "ear wax impaction",
    "eating disorder",
    "ectopic pregnancy",
    "eczema",
    "endometriosis",
    "envenomation from spider or animal bite",
    "epididymitis",
    "erectile dysfunction",
    "esophagitis",
    "eustachian tube dysfunction (ear disorder)",
    "eye alignment disorder",
    "fibromyalgia",
    "flu",
    "fluid overload",
    "food allergy",
    "fracture of the arm",
    "fracture of the facial bones",
    "fracture of the leg",
    "fracture of the rib",
    "fungal infection of the hair",
    "fungal infection of the skin",
    "gallstone",
    "ganglion cyst",
    "gastritis",
    "gastroduodenal ulcer",
    "gastroesophageal reflux disease (gerd)",
    "gastrointestinal hemorrhage",
    "glaucoma",
    "gout",
    "gum disease",
    "head and neck cancer",
    "heart attack",
    "heart block",
    "heart failure",
    "hemangioma",
    "hemiplegia",
    "hemorrhoids",
    "hepatitis due to a toxin",
    "herniated disk",
    "herpangina",
    "hiatal hernia",
    "hydronephrosis",
    "hyperemesis gravidarum",
    "hyperkalemia",
    "hypertensive heart disease",
    "hypoglycemia",
    "hypokalemia",
    "hyponatremia",
    "hypovolemia",
    "idiopathic absence of menstruation",
    "idiopathic excessive menstruation",
    "idiopathic irregular menstrual cycle",
    "idiopathic painful menstruation",
    "ileus",
    "impetigo",
    "impulse control disorder",
    "indigestion",
    "infectious gastroenteritis",
    "ingrown toe nail",
    "inguinal hernia",
    "injury to the arm",
    "injury to the face",
    "injury to the leg",
    "injury to the shoulder",
    "injury to the trunk",
    "insect bite",
    "interstitial lung disease",
    "intestinal disease",
    "intestinal obstruction",
    "intracerebral hemorrhage",
    "intracranial hemorrhage",
    "iridocyclitis",
    "iron deficiency anemia",
    "irritable bowel syndrome",
    "ischemic heart disease",
    "itching of unknown cause",
    "jaw disorder",
    "joint effusion",
    "kidney stone",
    "labyrinthitis",
    "laryngitis",
    "lateral epicondylitis (tennis elbow)",
    "lipoma",
    "liver disease",
    "lymphadenitis",
    "lymphedema",
    "macular degeneration",
    "marijuana abuse",
    "missed abortion",
    "mitral valve disease",
    "molluscum contagiosum",
    "mononeuritis",
    "mononucleosis",
    "multiple sclerosis",
    "muscle spasm",
    "myopia",
    "nasal polyp",
    "neuralgia",
    "neurosis",
    "noninfectious gastroenteritis",
    "nose disorder",
    "obsessive compulsive disorder (ocd)",
    "obstructive sleep apnea (osa)",
    "onychomycosis",
    "oppositional disorder",
    "oral mucosal lesion",
    "oral thrush (yeast infection)",
    "osteoarthritis",
    "osteoporosis",
    "otitis externa (swimmer's ear)",
    "otitis media",
    "ovarian cyst",
    "pain after an operation",
    "pain disorder affecting the neck",
    "panic disorder",
    "parkinson disease",
    "paronychia",
    "paroxysmal supraventricular tachycardia",
    "paroxysmal ventricular tachycardia",
    "pelvic inflammatory disease",
    "pelvic organ prolapse",
    "peripheral nerve disorder",
    "peritonitis",
    "personality disorder",
    "pilonidal cyst",
    "pleural effusion",
    "pneumonia",
    "post-traumatic stress disorder (ptsd)",
    "postpartum depression",
    "premature ventricular contractions (pvcs)",
    "problem during pregnancy",
    "prostatitis",
    "psoriasis",
    "psychotic disorder",
    "pulmonary congestion",
    "pulmonary embolism",
    "pulmonary hypertension",
    "pyelonephritis",
    "pyogenic skin infection",
    "rectal disorder",
    "rheumatoid arthritis",
    "rosacea",
    "sarcoidosis",
    "schizophrenia",
    "sciatica",
    "scleroderma",
    "seasonal allergies (hay fever)",
    "sebaceous cyst",
    "seborrheic dermatitis",
    "seborrheic keratosis",
    "sensorineural hearing loss",
    "sepsis",
    "shingles (herpes zoster)",
    "sialoadenitis",
    "sickle cell crisis",
    "sinus bradycardia",
    "skin cancer",
    "skin disorder",
    "skin pigmentation disorder",
    "skin polyp",
    "smoking or tobacco addiction",
    "social phobia",
    "spinal stenosis",
    "spondylitis",
    "spondylolisthesis",
    "spondylosis",
    "spontaneous abortion",
    "sprain or strain",
    "strep throat",
    "stroke",
    "stye",
    "teething syndrome",
    "temporary or benign blood in urine",
    "temporomandibular joint disorder",
    "tendinitis",
    "threatened pregnancy",
    "thrombophlebitis",
    "tietze syndrome",
    "tonsillar hypertrophy",
    "tonsillitis",
    "tooth abscess",
    "tooth disorder",
    "transient ischemic attack",
    "trichomonas infection",
    "ulcerative colitis",
    "urethral disorder",
    "urethritis",
    "urge incontinence",
    "urinary tract infection",
    "urinary tract obstruction",
    "uterine fibroids",
    "vaginal cyst",
    "vaginal yeast infection",
    "vaginitis",
    "varicocele of the testicles",
    "venous insufficiency",
    "viral exanthem",
    "viral warts",
    "vitreous degeneration",
    "vulvodynia",
    "white blood cell disease",
    "yeast infection"
  ]
};

export const MODEL_DIAGNOSES: Record<ModelKey, string[]> = {
  lr_full: ARCHIVED_MODEL_DIAGNOSES.cw_full,
  ae_clf_full: ARCHIVED_MODEL_DIAGNOSES.ae_t300,
  cw_full: ARCHIVED_MODEL_DIAGNOSES.cw_full,
  ablation_study: Array.from(
    new Set([
      ...ARCHIVED_MODEL_DIAGNOSES.ae_t100,
      ...ARCHIVED_MODEL_DIAGNOSES.ae_t200,
      ...ARCHIVED_MODEL_DIAGNOSES.ae_t300,
    ])
  ),
};

export const MODEL_DIAGNOSES_LABELS: Record<ModelKey, string> = {
  lr_full: "Logistic Regression diagnosis coverage (current reference set)",
  ae_clf_full: "Autoencoder MLP Classifier diagnosis coverage (current reference set)",
  cw_full: "Baseline MLP Classifier diagnosis coverage (current reference set)",
  ablation_study:
    "Threshold study diagnosis coverage (Autoencoder MLP Classifier Threshold 100, Threshold 200, and Threshold 300)",
};
